[package]
name = "sigma-webservice"
version = "0.1.0"
authors = ["khmhmm <khmhmm@ya.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "^3"
bytes = "1.0"
futures = "^0.3"
lazy_static = "^1"
