-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public."ActionsDescription"
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    description text,
    PRIMARY KEY (id)
);

CREATE TABLE public."ActionsJournal"
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    user_id bigint NOT NULL,
    action_id integer NOT NULL,
    date date,
    PRIMARY KEY (id)
);

CREATE TABLE public."Authors"
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name text,
    birthday date,
    zodiac_id smallint,
    PRIMARY KEY (id)
);

CREATE TABLE public."Categories"
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name text,
    PRIMARY KEY (id)
);

CREATE TABLE public."Files"
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    path text,
    PRIMARY KEY (id)
);

CREATE TABLE public."OrderMakers"
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    is_organization boolean,
    contact_name text,
    address text,
    phone text,
    title text,
    PRIMARY KEY (id)
);

CREATE TABLE public."Orders"
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    author_id bigint,
    name text,
    category_id bigint,
    year integer,
    type_id bigint,
    typography_id bigint,
    ordermaker_id bigint,
    price real,
    picture_id bigint,
    file_id bigint,
    status smallint,
    PRIMARY KEY (id)
);

CREATE TABLE public."PaperTypes"
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name text,
    PRIMARY KEY (id)
);

CREATE TABLE public."Pictures"
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    path text,
    PRIMARY KEY (id)
);

CREATE TABLE public."Roles"
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name text,
    PRIMARY KEY (id)
);

CREATE TABLE public."Typography"
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name text,
    address text,
    phone text,
    PRIMARY KEY (id)
);

CREATE TABLE public."Users"
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    role_id smallint NOT NULL,
    name text,
    hash text,
    salt text,
    PRIMARY KEY (id)
);

CREATE TABLE public."Zodiac"
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name text,
    PRIMARY KEY (id)
);

ALTER TABLE public."ActionsJournal"
    ADD FOREIGN KEY (action_id)
    REFERENCES public."ActionsDescription" (id)
    NOT VALID;


ALTER TABLE public."ActionsJournal"
    ADD FOREIGN KEY (user_id)
    REFERENCES public."Users" (id)
    NOT VALID;


ALTER TABLE public."Authors"
    ADD FOREIGN KEY (zodiac_id)
    REFERENCES public."Zodiac" (id)
    NOT VALID;


ALTER TABLE public."Orders"
    ADD FOREIGN KEY (author_id)
    REFERENCES public."Authors" (id)
    NOT VALID;


ALTER TABLE public."Orders"
    ADD FOREIGN KEY (category_id)
    REFERENCES public."Categories" (id)
    NOT VALID;


ALTER TABLE public."Orders"
    ADD FOREIGN KEY (file_id)
    REFERENCES public."Files" (id)
    NOT VALID;


ALTER TABLE public."Orders"
    ADD FOREIGN KEY (ordermaker_id)
    REFERENCES public."OrderMakers" (id)
    NOT VALID;


ALTER TABLE public."Orders"
    ADD FOREIGN KEY (picture_id)
    REFERENCES public."Pictures" (id)
    NOT VALID;


ALTER TABLE public."Orders"
    ADD FOREIGN KEY (type_id)
    REFERENCES public."PaperTypes" (id)
    NOT VALID;


ALTER TABLE public."Orders"
    ADD FOREIGN KEY (typography_id)
    REFERENCES public."Typography" (id)
    NOT VALID;


ALTER TABLE public."Users"
    ADD FOREIGN KEY (role_id)
    REFERENCES public."Roles" (id)
    NOT VALID;

END;
